# Generated by Django 6.0.5 on 2026-05-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('achevee', 'Achevée'), ('livree', 'Livrée')], default='debuter', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client')),
            ],
        ),
    ]
