# Generated by Django 6.0.5 on 2026-06-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='depense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
