# Generated by Django 6.0.5 on 2026-05-22 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MesureFemme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaule_dos', models.FloatField(blank=True, null=True)),
                ('tour_poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_manche', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('carrure_devant', models.FloatField(blank=True, null=True)),
                ('carrure_dos', models.FloatField(blank=True, null=True)),
                ('longueur_sein', models.FloatField(blank=True, null=True)),
                ('longueur_taille', models.FloatField(blank=True, null=True)),
                ('longueur_corsage', models.FloatField(blank=True, null=True)),
                ('tour_taille', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('tour_hanche', models.FloatField(blank=True, null=True)),
                ('longueur_clotop', models.FloatField(blank=True, null=True)),
                ('longueur_robe', models.FloatField(blank=True, null=True)),
                ('longueur_jupe', models.FloatField(blank=True, null=True)),
                ('longueur_chambrage_dos', models.FloatField(blank=True, null=True)),
                ('longueur_bohumba', models.FloatField(blank=True, null=True)),
                ('ecart_seins', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='MesureHomme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaule_dos', models.FloatField(blank=True, null=True)),
                ('tour_poitrine', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('longueur_manche', models.FloatField(blank=True, null=True)),
                ('longueur_bohumba', models.FloatField(blank=True, null=True)),
                ('tour_cou', models.FloatField(blank=True, null=True)),
                ('longueur_chemise', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('tour_hanche', models.FloatField(blank=True, null=True)),
                ('longueur_pantalon', models.FloatField(blank=True, null=True)),
                ('longueur_genou', models.FloatField(blank=True, null=True)),
                ('tour_genou', models.FloatField(blank=True, null=True)),
                ('tour_bas', models.FloatField(blank=True, null=True)),
                ('tour_cuisse', models.FloatField(blank=True, null=True)),
                ('longueur_culotte', models.FloatField(blank=True, null=True)),
                ('longueur_gilet', models.FloatField(blank=True, null=True)),
                ('longueur_veste', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
