# Generated by Django 6.0.5 on 2026-06-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesurefemme',
            old_name='longueur_taille',
            new_name='longueur_genou',
        ),
        migrations.AddField(
            model_name='mesurefemme',
            name='longueur_pantalon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurefemme',
            name='longueur_taille_devant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurefemme',
            name='longueur_taille_dos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurefemme',
            name='tour_bas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurefemme',
            name='tour_encolure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
