# Generated by Django 6.0.5 on 2026-06-10 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_modeleatelier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleatelier',
            name='tailleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to=settings.AUTH_USER_MODEL),
        ),
    ]
