# Generated by Django 6.0.5 on 2026-06-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_modeleatelier_tailleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleatelier',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
